<template>
  <div class="detailsBox">
    <!-- <table
      class="tableizer-table content"
      v-show="rentInfomation.id === 1"
    >
      <thead>
        <tr class="tableizer-firstrow">
          <th >主体</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>系列</td>
          <td>T 系列</td>
        </tr>
        <tr>
          <td>颜色</td>
          <td>黑色</td>
        </tr>
        <tr>
          <td>平台</td>
          <td>Intel</td>
        </tr>
        <tr>
          <td>操作系统</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>操作系统</td>
          <td>Windows 10</td>
        </tr>
        <tr>
          <td>处理器</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>CPU类型</td>
          <td>酷睿双核</td>
        </tr>
        <tr>
          <td>CPU型号</td>
          <td>i5-6200U</td>
        </tr>
        <tr>
          <td>二级缓存</td>
          <td>3MB</td>
        </tr>
        <tr>
          <td>核心</td>
          <td>双核</td>
        </tr>
        <tr>
          <td>内存</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内存容量</td>
          <td>8GB</td>
        </tr>
        <tr>
          <td>内存类型</td>
          <td>DDR4 2133</td>
        </tr>
        <tr>
          <td>插槽数量</td>
          <td>2 x SO-DIMM</td>
        </tr>
        <tr>
          <td>硬盘</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>硬盘容量</td>
          <td>256GB SSD</td>
        </tr>
        <tr>
          <td>显卡</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>显卡型号</td>
          <td>NVIDIA GeForce 940MX</td>
        </tr>
        <tr>
          <td>显存容量</td>
          <td>2G独显</td>
        </tr>
        <tr>
          <td>光驱</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>光驱类型</td>
          <td>无光驱</td>
        </tr>
        <tr>
          <td>显示器</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>屏幕尺寸</td>
          <td>14英寸</td>
        </tr>
        <tr>
          <td>屏幕规格</td>
          <td>14.0英寸</td>
        </tr>
        <tr>
          <td>显示比例</td>
          <td>宽屏16：9</td>
        </tr>
        <tr>
          <td>屏幕类型</td>
          <td>LED背光</td>
        </tr>
        <tr>
          <td>通信</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内置蓝牙</td>
          <td>有</td>
        </tr>
        <tr>
          <td>局域网</td>
          <td>10/100/1000Mbps</td>
        </tr>
        <tr>
          <td>无线局域网</td>
          <td>有</td>
        </tr>
        <tr>
          <td>内置3G</td>
          <td>无</td>
        </tr>
        <tr>
          <td>内置3G模块</td>
          <td>有</td>
        </tr>
        <tr>
          <td>端口</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>音频端口</td>
          <td>耳机、麦克风二合一接口</td>
        </tr>
        <tr>
          <td>显示端口</td>
          <td>HDMI接口</td>
        </tr>
        <tr>
          <td>RJ45</td>
          <td>1个</td>
        </tr>
        <tr>
          <td>音效系统</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>扬声器</td>
          <td>内置扬声器</td>
        </tr>
        <tr>
          <td>杜比音效</td>
          <td>支持</td>
        </tr>
        <tr>
          <td>内置麦克风</td>
          <td>有</td>
        </tr>
        <tr>
          <td>输入设备</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>键盘</td>
          <td>全尺寸键盘</td>
        </tr>
        <tr>
          <td>触摸板</td>
          <td>多点触控</td>
        </tr>
        <tr>
          <td>指点杆</td>
          <td>有</td>
        </tr>
        <tr>
          <td>其它设备</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>网络摄像头</td>
          <td>有</td>
        </tr>
        <tr>
          <td>摄像头像素</td>
          <td>720p</td>
        </tr>
        <tr>
          <td>指纹识别</td>
          <td>有</td>
        </tr>
        <tr>
          <td>读卡器</td>
          <td>有</td>
        </tr>
        <tr>
          <td>电源</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>续航时间</td>
          <td>2-5小时</td>
        </tr>
        <tr>
          <td>电源适配器</td>
          <td>100-240V自适应交流电源适配器</td>
        </tr>
        <tr>
          <td>机器规格</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>净重</td>
          <td>重约1.78kg</td>
        </tr>
      </tbody>
    </table>
    <table
      class="tableizer-table content"
      v-show="rentInfomation.id === 2"
    >
      <thead>
        <tr class="tableizer-firstrow">
          <th>主体</th>
          <th>&nbsp;</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>系列</td>
          <td>X 系列</td>
        </tr>
        <tr>
          <td>颜色</td>
          <td>黑色</td>
        </tr>
        <tr>
          <td>平台</td>
          <td>Intel</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>操作系统</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>操作系统</td>
          <td>Windows</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>处理器</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>CPU类型</td>
          <td>酷睿双核i5处理器</td>
        </tr>
        <tr>
          <td>CPU型号</td>
          <td>i5-6200U</td>
        </tr>
        <tr>
          <td>CPU速度</td>
          <td>主频2.3GHz睿频至2.8GHz</td>
        </tr>
        <tr>
          <td>三级缓存</td>
          <td>3M</td>
        </tr>
        <tr>
          <td>核心</td>
          <td>双核</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内存</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内存容量</td>
          <td>8GB</td>
        </tr>
        <tr>
          <td>内存类型</td>
          <td>DDR4</td>
        </tr>
        <tr>
          <td>插槽数量</td>
          <td>1 x SO-DIMM</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>硬盘</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>硬盘类型</td>
          <td>固态硬盘</td>
        </tr>
        <tr>
          <td>硬盘容量</td>
          <td>256G SSD</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>显卡</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>类型</td>
          <td>英特尔核芯显卡</td>
        </tr>
        <tr>
          <td>显示芯片</td>
          <td>Intel HD Graphics 520</td>
        </tr>
        <tr>
          <td>显存容量</td>
          <td>共享系统内存（集成）</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>光驱</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>光驱类型</td>
          <td>无光驱</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>显示器</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>屏幕规格</td>
          <td>12.5英寸</td>
        </tr>
        <tr>
          <td>显示比例</td>
          <td>宽屏16：9</td>
        </tr>
        <tr>
          <td>物理分辨率</td>
          <td>1366 x 768</td>
        </tr>
        <tr>
          <td>屏幕类型</td>
          <td>LED背光</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>通信</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内置蓝牙</td>
          <td>蓝牙4.0</td>
        </tr>
        <tr>
          <td>局域网</td>
          <td>10/100/1000Mbps</td>
        </tr>
        <tr>
          <td>无线局域网</td>
          <td>有</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>端口</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>音频端口</td>
          <td>耳机、麦克风二合一接口</td>
        </tr>
        <tr>
          <td>显示端口</td>
          <td>HDMI x 1/ Mini DP x 1</td>
        </tr>
        <tr>
          <td>RJ45</td>
          <td>1个</td>
        </tr>
        <tr>
          <td>USB3.0</td>
          <td>3个</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>音效系统</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>扬声器</td>
          <td>内置扬声器</td>
        </tr>
        <tr>
          <td>杜比音效</td>
          <td>支持</td>
        </tr>
        <tr>
          <td>内置麦克风</td>
          <td>有</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>输入设备</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>键盘</td>
          <td>全尺寸键盘</td>
        </tr>
        <tr>
          <td>触摸板</td>
          <td>多点触控</td>
        </tr>
        <tr>
          <td>指点杆</td>
          <td>有</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>其它设备</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>网络摄像头</td>
          <td>有</td>
        </tr>
        <tr>
          <td>摄像头像素</td>
          <td>720p</td>
        </tr>
        <tr>
          <td>指纹识别</td>
          <td>有</td>
        </tr>
        <tr>
          <td>读卡器</td>
          <td>4合1读卡器</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>电源</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>电池</td>
          <td>内置3芯+外置3芯电池</td>
        </tr>
        <tr>
          <td>续航时间</td>
          <td>约5-6小时, 具体时间视使用环境而定</td>
        </tr>
        <tr>
          <td>电源适配器</td>
          <td>100-240V自适应交流电源适配器</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>机器规格</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>净重</td>
          <td>重约1.42Kg</td>
        </tr>
      </tbody>
    </table>
    <table
      class="tableizer-table content"
      v-show="rentInfomation.id === 3"
    >
      <thead>
        <tr class="tableizer-firstrow">
          <th>主体</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>产品型号</td>
          <td>E460系列</td>
        </tr>
        <tr>
          <td>平台</td>
          <td>Intel</td>
        </tr>
        <tr>
          <td>操作系统</td>
          <td>Windows</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>处理器</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>CPU类型</td>
          <td>Intel Core i5 处理器</td>
        </tr>
        <tr>
          <td>CPU型号</td>
          <td>i5</td>
        </tr>
        <tr>
          <td>CPU速度</td>
          <td>不低于2.3GHz</td>
        </tr>
        <tr>
          <td>核心/线程</td>
          <td>双核四线程</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内存</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内存容量</td>
          <td>8GB</td>
        </tr>
        <tr>
          <td>内存类型</td>
          <td>DDR3L</td>
        </tr>
        <tr>
          <td>插槽数量</td>
          <td>2个</td>
        </tr>
        <tr>
          <td>最大支持容量</td>
          <td>16GB</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>硬盘</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>硬盘类型</td>
          <td>固态硬盘</td>
        </tr>
        <tr>
          <td>硬盘容量</td>
          <td>240G</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>显卡</td>
        </tr>
        <tr>
          <td>显卡类型</td>
          <td>独立显卡</td>
        </tr>
        <tr>
          <td>显卡型号</td>
          <td>AMD Radeon R5 M330</td>
        </tr>
        <tr>
          <td>显存容量</td>
          <td>2G</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>光驱</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>光驱类型</td>
          <td>随机发货</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>显示器</td>
        </tr>
        <tr>
          <td>屏幕尺寸</td>
          <td>14英寸</td>
        </tr>
        <tr>
          <td>显示比例</td>
          <td>宽屏16:9</td>
        </tr>
        <tr>
          <td>物理分辨率</td>
          <td>1366*768</td>
        </tr>
        <tr>
          <td>屏幕类型</td>
          <td>LED 背光显示屏</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>通信</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>内置蓝牙</td>
          <td>随机发货</td>
        </tr>
        <tr>
          <td>无线网卡</td>
          <td>802.11ac/802.11bgn</td>
        </tr>
        <tr>
          <td>有线网卡</td>
          <td>1000Mbps网卡</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>I/O端口</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>音频端口</td>
          <td>耳机、麦克风二合一接口</td>
        </tr>
        <tr>
          <td>显示端口</td>
          <td>HDMI</td>
        </tr>
        <tr>
          <td>USB</td>
          <td>3.0*3个</td>
        </tr>
        <tr>
          <td>type-c 接口</td>
          <td>无</td>
        </tr>
        <tr>
          <td>RJ45(以太网口)</td>
          <td>1个</td>
        </tr>
        <tr>
          <td>读卡器</td>
          <td>4合1读卡器</td>
        </tr>
        <tr>
          <td>其他接口</td>
          <td>电源接口,ExpressCard</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>音效系统</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>扬声器</td>
          <td>内置扬声器</td>
        </tr>
        <tr>
          <td>内置麦克风</td>
          <td>有</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>输入设备</td>
        </tr>
        <tr>
          <td>键盘</td>
          <td>全尺寸键盘</td>
        </tr>
        <tr>
          <td>触摸板</td>
          <td>多点触摸板</td>
        </tr>
        <tr>
          <td>指点杆</td>
          <td>Trackpoint指点杆</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>其他设备</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>指纹识别</td>
          <td>随机发货</td>
        </tr>
        <tr>
          <td>网络摄像头</td>
          <td>随机发货</td>
        </tr>
        <tr>
          <td>摄像头像素</td>
          <td>随机发货</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>电源</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>电池</td>
          <td>6芯锂电池</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>机器规格</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>尺寸</td>
          <td>约339mm*239mm*24.4mm</td>
        </tr>
        <tr>
          <td>净重</td>
          <td>约1.92kg</td>
        </tr>
        <tr>
          <td>包装清单</td>
          <td>笔记本主机*1/电源适配器*1/电源线*1</td>
        </tr>
      </tbody>
    </table> -->
    
    <table
      border="1"
      cellspacing="0"
      cellpadding="0"
      class="tableizer-table content"
      v-show="rentInfomation.id === 1"
    >
      <tbody>
        <tr class="tableizer-firstrow">
          <th colspan="2">主体</th>
        </tr>
        <tr>
          <td>系列</td>
          <td>T 系列</td>
        </tr>
        <tr>
          <td>颜色</td>
          <td>黑色</td>
        </tr>
        <tr>
          <td>平台</td>
          <td>Intel</td>
        </tr>
        <tr>
          <th colspan="2">操作系统</th>
        </tr>
        <tr>
          <td>操作系统</td>
          <td>Windows 10</td>
        </tr>
        <tr>
          <th colspan="2">处理器</th>
        </tr>
        <tr>
          <td>CPU类型</td>
          <td>酷睿双核</td>
        </tr>
        <tr>
          <td>CPU型号</td>
          <td>i5-6200U</td>
        </tr>
        <tr>
          <td>二级缓存</td>
          <td>3MB</td>
        </tr>
        <tr>
          <td>核心</td>
          <td>双核</td>
        </tr>
        <tr>
          <th colspan="2">内存</th>
        </tr>
        <tr>
          <td>内存容量</td>
          <td>8GB</td>
        </tr>
        <tr>
          <td>内存类型</td>
          <td>DDR4 2133</td>
        </tr>
        <tr>
          <td>插槽数量</td>
          <td>2 x SO-DIMM</td>
        </tr>
        <tr>
          <th colspan="2">硬盘</th>
        </tr>
        <tr>
          <td>硬盘容量</td>
          <td>256GB SSD</td>
        </tr>
        <tr>
          <th colspan="2">显卡</th>
        </tr>
        <tr>
          <td>显卡型号</td>
          <td>NVIDIA GeForce 940MX</td>
        </tr>
        <tr>
          <td>显存容量</td>
          <td>2G独显</td>
        </tr>
        <tr>
          <th colspan="2">光驱</th>
        </tr>
        <tr>
          <td>光驱类型</td>
          <td>无光驱</td>
        </tr>
        <tr>
          <th colspan="2">显示器</th>
        </tr>
        <tr>
          <td>屏幕尺寸</td>
          <td>14英寸</td>
        </tr>
        <tr>
          <td>屏幕规格</td>
          <td>14.0英寸</td>
        </tr>
        <tr>
          <td>显示比例</td>
          <td>宽屏16：9</td>
        </tr>
        <tr>
          <td>屏幕类型</td>
          <td>LED背光</td>
        </tr>
        <tr>
          <th colspan="2">通信</th>
        </tr>
        <tr>
          <td>内置蓝牙</td>
          <td>有</td>
        </tr>
        <tr>
          <td>局域网</td>
          <td>10/100/1000Mbps</td>
        </tr>
        <tr>
          <td>无线局域网</td>
          <td>有</td>
        </tr>
        <tr>
          <td>内置3G</td>
          <td>无</td>
        </tr>
        <tr>
          <td>内置3G模块</td>
          <td>有</td>
        </tr>
        <tr>
          <th colspan="2">端口</th>
        </tr>
        <tr>
          <td>音频端口</td>
          <td>耳机、麦克风二合一接口</td>
        </tr>
        <tr>
          <td>显示端口</td>
          <td>HDMI接口</td>
        </tr>
        <tr>
          <td>RJ45</td>
          <td>1个</td>
        </tr>
        <tr>
          <th colspan="2">音效系统</th>
        </tr>
        <tr>
          <td>扬声器</td>
          <td>内置扬声器</td>
        </tr>
        <tr>
          <td>杜比音效</td>
          <td>支持</td>
        </tr>
        <tr>
          <td>内置麦克风</td>
          <td>有</td>
        </tr>
        <tr>
          <th colspan="2">输入设备</th>
        </tr>
        <tr>
          <td>键盘</td>
          <td>全尺寸键盘</td>
        </tr>
        <tr>
          <td>触摸板</td>
          <td>多点触控</td>
        </tr>
        <tr>
          <td>指点杆</td>
          <td>有</td>
        </tr>
        <tr>
          <th colspan="2">其它设备</th>
        </tr>
        <tr>
          <td>网络摄像头</td>
          <td>有</td>
        </tr>
        <tr>
          <td>摄像头像素</td>
          <td>720p</td>
        </tr>
        <tr>
          <td>指纹识别</td>
          <td>有</td>
        </tr>
        <tr>
          <td>读卡器</td>
          <td>有</td>
        </tr>
        <tr>
          <th colspan="2">电源</th>
        </tr>
        <tr>
          <td>续航时间</td>
          <td>2-5小时</td>
        </tr>
        <tr>
          <td>电源适配器</td>
          <td>100-240V自适应交流电源适配器</td>
        </tr>
        <tr>
          <th colspan="2">机器规格</th>
        </tr>
        <tr>
          <td>净重</td>
          <td>重约1.78kg</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

  

<script>
const test = {
  template: "#test",
};
export default {
  props: {
    rentInfomation: {
      type: Object,
      default() {
        return {};
      },
    },
  },
  components: {},
};
</script>

<style lang="scss" scoped>
.content {
  width: 770px;
  height: auto;
  overflow: hidden;
}
table.tableizer-table {
  font-size: 12px;
  border: 1px solid #ccc;
  font-family: PingFangSC;
}
.tableizer-table td {
  // padding: 4px;
  // margin: 3px;
  line-height: 30px;
  text-align: center;
  color: #000000;
  // border: 1px solid #ccc;
}
.tableizer-table th {
  color: #000000;
  line-height: 30px;
  font-weight: bold;
}
// table {
//   width: 770px;
//   line-height: 30px;
//   color: #000;
// }
// tr,
// td {
//   color: #000;
//   // border: 1px solid red;
// }
</style>
